name: android2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  intl: ^0.20.2
  device_preview: ^1.2.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  get_it: ^8.0.3
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
